import { useParams, Link } from 'react-router-dom';

const LAST_UPDATED = 'June 2, 2026';
const COMPANY = 'BullSage';
const DOMAIN = 'bullsage.co';
const EMAIL = 'legal@bullsage.co';

// ─── DISCLAIMER ─────────────────────────────────────────────────────────────
function Disclaimer({ lang }) {
  return (
    <Article
      lang={lang}
      en={{
        title: 'Investment Disclaimer & Risk Disclosure',
        sections: [
          {
            heading: '1. Educational Content Only',
            body: `BullSage provides AI-generated stock analysis, investment framework evaluations, and financial educational content solely for informational and educational purposes. Nothing on ${DOMAIN} or in any BullSage report constitutes investment advice, financial advice, trading advice, or any other type of advice. BullSage is not a licensed investment advisor, broker-dealer, financial planner, or any other type of regulated financial professional.`,
          },
          {
            heading: '2. Not a Licensed Financial Advisor',
            body: `BullSage does not hold, and does not claim to hold, any financial services license in Singapore (MAS), Hong Kong (SFC), Australia (ASIC/AFSL), Malaysia (SC), or any other jurisdiction. Our content is provided under the "general information" or "educational content" exemption available in many jurisdictions and must not be relied upon as a substitute for professional licensed financial advice.`,
          },
          {
            heading: '3. AI-Generated Content Limitations',
            body: `Our analysis is generated by artificial intelligence (Google Gemini) using publicly available financial data sourced from third-party providers (yfinance, Alpha Vantage). AI models can produce inaccurate, incomplete, or outdated information ("hallucinations"). All financial figures, ratios, valuations, and projections presented in BullSage reports:\n\n• May contain errors or be outdated\n• Should be independently verified before making any financial decision\n• Are not audited or guaranteed for accuracy\n• Reflect simulated application of historical frameworks, not real-time licensed analysis`,
          },
          {
            heading: '4. Investment Risk Warning',
            body: `All investments involve risk. The value of investments can go down as well as up. Past performance is not a reliable indicator of future results. You may lose some or all of your invested capital. Before making any investment decision, you should carefully consider your investment objectives, financial situation, and risk tolerance, and seek advice from a licensed financial advisor.`,
          },
          {
            heading: '5. "Master Framework" Simulations',
            body: `The investment master verdicts presented by BullSage (including simulations of Buffett, Graham, Lynch, Munger, Fisher, Greenblatt, Dalio, Wood, Bogle, and Klarman frameworks) are AI-generated educational simulations based on publicly available descriptions of these investors' stated philosophies. They do not represent the actual views, endorsements, or recommendations of these investors or their affiliated entities. These names are used for educational reference only.`,
          },
          {
            heading: '6. Educational Trade Plans',
            body: `Any "trade plan," "entry price," "stop-loss," "position size," or "take profit" information presented on BullSage is provided strictly as an educational scenario simulation. It is not a trade recommendation, signal, or instruction. Do not execute any trade based solely on BullSage-generated trade plans without consulting a licensed financial professional.`,
          },
          {
            heading: '7. No Reliance',
            body: `BullSage, its owners, employees, contractors, and AI systems shall not be liable for any loss or damage arising from your reliance on information obtained from our platform. You acknowledge that you use BullSage at your own risk.`,
          },
          {
            heading: '8. Jurisdiction',
            body: `This disclaimer applies to users in all jurisdictions, including but not limited to Singapore, Hong Kong, Malaysia, Australia, Taiwan, Canada, and the United States. Users are responsible for ensuring that their use of BullSage complies with applicable local laws.`,
          },
        ],
      }}
      zh={{
        title: '投资免责声明与风险披露',
        sections: [
          {
            heading: '1. 仅限教育性内容',
            body: `BullSage 提供的 AI 生成股票分析、投资框架评估及金融教育内容，仅供参考和教育目的。${DOMAIN} 上的任何内容及 BullSage 报告均不构成投资建议、财务建议、交易建议或任何其他类型的专业建议。BullSage 不是持牌投资顾问、经纪商、财务规划师或其他受监管的金融专业人士。`,
          },
          {
            heading: '2. 非持牌金融顾问',
            body: `BullSage 未持有，也不声称持有新加坡（MAS）、香港（SFC）、澳大利亚（ASIC/AFSL）、马来西亚（SC）或其他任何司法管辖区的金融服务牌照。我们的内容依据许多司法管辖区的"一般信息"或"教育性内容"豁免条款提供，不得作为持牌专业金融建议的替代品。`,
          },
          {
            heading: '3. AI 生成内容的局限性',
            body: `我们的分析由人工智能（Google Gemini）使用来自第三方供应商（yfinance、Alpha Vantage）的公开金融数据生成。AI 模型可能产生不准确、不完整或过时的信息（"幻觉"）。BullSage 报告中呈现的所有财务数据、比率、估值和预测：\n\n• 可能包含错误或已过时\n• 在做出任何财务决定前应独立核实\n• 未经审计，不保证准确性\n• 反映历史框架的模拟应用，而非实时持牌分析`,
          },
          {
            heading: '4. 投资风险警示',
            body: `所有投资均涉及风险。投资价值可能上升也可能下降。过往表现不是未来结果的可靠指标。您可能损失部分或全部投资本金。在做出任何投资决定之前，您应仔细考虑您的投资目标、财务状况和风险承受能力，并寻求持牌财务顾问的建议。`,
          },
          {
            heading: '5. "大师框架"模拟声明',
            body: `BullSage 呈现的投资大师裁决（包括巴菲特、格雷厄姆、林奇、芒格、费雪、格林布拉特、达利欧、伍德、博格尔和卡拉曼框架的模拟）是 AI 根据这些投资者公开陈述的投资哲学生成的教育性模拟。这些内容不代表上述投资者或其关联实体的实际观点、背书或建议。这些名字仅用于教育参考目的。`,
          },
          {
            heading: '6. 教育性交易计划',
            body: `BullSage 提供的任何"交易计划"、"进场价位"、"止损"、"仓位规模"或"止盈"信息，均严格作为教育性情景模拟提供。这不是交易建议、信号或指令。未经持牌金融专业人士咨询，请勿仅凭 BullSage 生成的交易计划执行任何交易。`,
          },
          {
            heading: '7. 免除责任',
            body: `BullSage 及其所有者、员工、承包商和 AI 系统对因您依赖本平台信息而造成的任何损失或损害不承担责任。您确认使用 BullSage 的风险由您自行承担。`,
          },
          {
            heading: '8. 司法管辖范围',
            body: `本免责声明适用于所有司法管辖区的用户，包括但不限于新加坡、香港、马来西亚、澳大利亚、台湾、加拿大和美国。用户有责任确保其使用 BullSage 符合当地适用法律。`,
          },
        ],
      }}
    />
  );
}

// ─── TERMS OF SERVICE ────────────────────────────────────────────────────────
function Terms({ lang }) {
  return (
    <Article
      lang={lang}
      en={{
        title: 'Terms of Service',
        sections: [
          {
            heading: '1. Acceptance of Terms',
            body: `By accessing or using BullSage (${DOMAIN}), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our platform.`,
          },
          {
            heading: '2. Description of Service',
            body: `BullSage is an AI-powered investment education platform that provides stock analysis reports, investment framework evaluations, and educational trade simulations. All content is for educational purposes only. See our Investment Disclaimer for full risk disclosures.`,
          },
          {
            heading: '3. Eligibility',
            body: `You must be at least 18 years old to use BullSage. By using our service, you represent that you are of legal age and have the legal capacity to enter into this agreement in your jurisdiction.`,
          },
          {
            heading: '4. Account Registration',
            body: `You are responsible for maintaining the confidentiality of your account credentials. You agree to notify us immediately at ${EMAIL} if you suspect unauthorized use of your account. BullSage is not liable for any loss arising from unauthorized use of your account.`,
          },
          {
            heading: '5. Subscription Plans & Payments',
            body: `BullSage offers the following plans:\n\n• Free: 3 reports/month, 10 watchlist items\n• Single Report: $9 USD per report, 30-day access\n• Pro Monthly: $19 USD/month, unlimited reports\n• Pro Annual: $179 USD/year, unlimited reports\n• Founding Member: $299 USD one-time, lifetime access\n\nAll payments are processed by Stripe. By purchasing, you authorize us to charge your payment method. Prices are in USD. Applicable taxes may apply based on your jurisdiction.`,
          },
          {
            heading: '6. Refund Policy',
            body: `Single Report ($9): Refunds available within 24 hours if no report has been generated.\n\nPro Monthly/Annual: You may cancel at any time. Cancellation takes effect at the end of the current billing period. No partial refunds for unused time.\n\nFounding Member ($299): Due to the lifetime nature of this purchase, refunds are available within 7 days of purchase if you have not accessed Pro features. Contact ${EMAIL} to request a refund.\n\nWe reserve the right to refuse refunds in cases of suspected abuse or fraud.`,
          },
          {
            heading: '7. Free Tier Limitations',
            body: `Free accounts are limited to 3 AI-generated reports per month and 10 watchlist items. Report counts reset on the 1st of each calendar month. BullSage reserves the right to adjust free tier limits with 30 days notice.`,
          },
          {
            heading: '8. Acceptable Use',
            body: `You agree not to:\n\n• Resell, redistribute, or republish BullSage reports without written permission\n• Use our platform to provide licensed financial advice to third parties\n• Attempt to scrape, automate, or reverse-engineer our platform\n• Create multiple free accounts to circumvent usage limits\n• Use our service for any illegal purpose`,
          },
          {
            heading: '9. Intellectual Property',
            body: `BullSage retains all rights to our platform, AI systems, and brand. Individual AI-generated reports you purchase may be used for your personal investment research. You may not resell or publicly distribute reports without written consent.`,
          },
          {
            heading: '10. Disclaimer of Warranties',
            body: `BullSage is provided "as is" without warranties of any kind. We do not warrant that our service will be uninterrupted, error-free, or that AI-generated content will be accurate. See our full Investment Disclaimer.`,
          },
          {
            heading: '11. Limitation of Liability',
            body: `To the maximum extent permitted by law, BullSage's total liability for any claim arising from your use of the service shall not exceed the amount you paid to BullSage in the 12 months preceding the claim. BullSage shall not be liable for any indirect, incidental, special, or consequential damages, including investment losses.`,
          },
          {
            heading: '12. Governing Law',
            body: `These Terms are governed by the laws applicable in the jurisdiction where BullSage is registered. Any disputes shall be resolved through binding arbitration or the applicable courts in that jurisdiction.`,
          },
          {
            heading: '13. Changes to Terms',
            body: `We may update these Terms at any time. We will notify registered users by email at least 14 days before material changes take effect. Continued use after changes constitutes acceptance.`,
          },
          {
            heading: '14. Contact',
            body: `For questions about these Terms, contact us at ${EMAIL}.`,
          },
        ],
      }}
      zh={{
        title: '服务条款',
        sections: [
          {
            heading: '1. 条款接受',
            body: `访问或使用 BullSage（${DOMAIN}），即表示您同意受本服务条款约束。如果您不同意这些条款，请不要使用我们的平台。`,
          },
          {
            heading: '2. 服务描述',
            body: `BullSage 是一个 AI 驱动的投资教育平台，提供股票分析报告、投资框架评估和教育性交易模拟。所有内容仅供教育目的。完整风险披露请参阅我们的投资免责声明。`,
          },
          {
            heading: '3. 资格要求',
            body: `您必须年满 18 岁才能使用 BullSage。使用我们的服务，即表示您声明您已达到法定年龄，并在您所在司法管辖区具有签订本协议的法律能力。`,
          },
          {
            heading: '4. 账户注册',
            body: `您负责维护账户凭证的保密性。如果您怀疑账户被未授权使用，请立即通过 ${EMAIL} 通知我们。BullSage 对因未授权使用您的账户而造成的任何损失不承担责任。`,
          },
          {
            heading: '5. 订阅计划与付款',
            body: `BullSage 提供以下方案：\n\n• 免费版：每月 3 份报告，10 只自选股\n• 单报告：每份 9 美元，30 天访问权限\n• Pro 月订阅：每月 19 美元，无限报告\n• Pro 年订阅：每年 179 美元，无限报告\n• 创始终身会员：299 美元一次性付款，终身访问\n\n所有付款通过 Stripe 处理。购买即表示您授权我们向您的支付方式收费。价格以美元计算，根据您所在司法管辖区可能需缴纳适用税款。`,
          },
          {
            heading: '6. 退款政策',
            body: `单报告（9 美元）：如未生成报告，24 小时内可申请退款。\n\nPro 月/年订阅：可随时取消。取消在当前计费周期结束时生效。未使用时间不予部分退款。\n\n创始终身会员（299 美元）：鉴于终身购买的性质，如您未访问 Pro 功能，可在购买后 7 天内申请退款。请发送电子邮件至 ${EMAIL} 申请退款。\n\n我们保留在涉嫌滥用或欺诈情况下拒绝退款的权利。`,
          },
          {
            heading: '7. 免费版限制',
            body: `免费账户每月限制 3 份 AI 生成报告和 10 只自选股。报告次数在每个日历月的 1 日重置。BullSage 保留在提前 30 天通知的情况下调整免费版限制的权利。`,
          },
          {
            heading: '8. 可接受使用',
            body: `您同意不：\n\n• 未经书面许可转售、再分发或重新发布 BullSage 报告\n• 使用我们的平台向第三方提供持牌财务建议\n• 尝试抓取、自动化或逆向工程我们的平台\n• 创建多个免费账户以规避使用限制\n• 将我们的服务用于任何非法目的`,
          },
          {
            heading: '9. 知识产权',
            body: `BullSage 保留对我们平台、AI 系统和品牌的所有权利。您购买的个人 AI 生成报告可用于您的个人投资研究。未经书面同意，您不得转售或公开分发报告。`,
          },
          {
            heading: '10. 免责声明',
            body: `BullSage 按"现状"提供，不提供任何形式的保证。我们不保证服务不会中断、无错误，或 AI 生成的内容准确无误。请参阅完整的投资免责声明。`,
          },
          {
            heading: '11. 责任限制',
            body: `在法律允许的最大范围内，BullSage 对因您使用本服务而产生的任何索赔的总责任，不超过您在索赔前 12 个月内向 BullSage 支付的金额。BullSage 不对任何间接、附带、特殊或后果性损害（包括投资损失）承担责任。`,
          },
          {
            heading: '12. 适用法律',
            body: `本条款受 BullSage 注册所在司法管辖区的适用法律管辖。任何争议应通过有约束力的仲裁或该司法管辖区的适用法院解决。`,
          },
          {
            heading: '13. 条款变更',
            body: `我们可能随时更新本条款。我们将在重大变更生效前至少 14 天通过电子邮件通知注册用户。变更后继续使用即表示接受。`,
          },
          {
            heading: '14. 联系方式',
            body: `如对本条款有任何疑问，请通过 ${EMAIL} 联系我们。`,
          },
        ],
      }}
    />
  );
}

// ─── PRIVACY POLICY ─────────────────────────────────────────────────────────
function Privacy({ lang }) {
  return (
    <Article
      lang={lang}
      en={{
        title: 'Privacy Policy',
        sections: [
          {
            heading: '1. Who We Are',
            body: `BullSage operates ${DOMAIN}, an AI investment education platform. We are committed to protecting your personal data. Contact us at ${EMAIL} for any privacy inquiries.`,
          },
          {
            heading: '2. Data We Collect',
            body: `Account data: Email address, password (hashed), display name, language preference, account plan.\n\nUsage data: Stock tickers you analyze, watchlist items, report history, timestamps.\n\nPayment data: Payment transactions processed by Stripe. BullSage does not store credit card numbers. Stripe's privacy policy applies to payment data.\n\nTechnical data: IP address, browser type, device type, session data collected automatically.`,
          },
          {
            heading: '3. How We Use Your Data',
            body: `• Provide and improve BullSage services\n• Authenticate your account and manage subscriptions\n• Generate and cache AI analysis reports\n• Send transactional emails (account creation, payment receipts)\n• Enforce our Terms of Service and prevent fraud\n• Comply with legal obligations`,
          },
          {
            heading: '4. Legal Basis for Processing (GDPR & PDPA)',
            body: `Contract performance: Processing necessary to provide the service you signed up for.\n\nLegitimate interests: Fraud prevention, security, service improvement.\n\nConsent: Marketing communications (you can opt out at any time).\n\nLegal obligation: Compliance with applicable laws.`,
          },
          {
            heading: '5. Data Storage & Third-Party Processors',
            body: `Our key data processors:\n\n• Supabase (supabase.com): Database, authentication. Servers in ap-southeast-1 (Singapore). Supabase's privacy policy applies.\n• Stripe (stripe.com): Payment processing. Stripe is PCI-DSS certified.\n• Google (AI Studio / Gemini API): AI inference. Your query data (stock tickers, financial data) may be processed by Google. No personal identifying information is sent to Gemini.\n• Vercel (vercel.com): Frontend hosting. May log IP addresses.\n\nWe do not sell your personal data to third parties.`,
          },
          {
            heading: '6. International Data Transfers',
            body: `Your data is stored primarily in Singapore (ap-southeast-1). Some service providers may process data in the United States or Europe. These transfers are subject to appropriate safeguards under applicable data protection laws.`,
          },
          {
            heading: '7. Your Rights',
            body: `Depending on your jurisdiction, you have the right to:\n\n• Access: Request a copy of your personal data\n• Rectification: Correct inaccurate data\n• Erasure: Request deletion of your account and data\n• Portability: Receive your data in a structured format\n• Objection: Object to processing based on legitimate interests\n• Withdrawal of consent: Withdraw consent at any time\n\nTo exercise these rights, email ${EMAIL}. We will respond within 30 days.`,
          },
          {
            heading: '8. Data Retention',
            body: `Active accounts: Data retained for the duration of your account plus 12 months.\n\nDeleted accounts: Core account data deleted within 30 days. Anonymized usage data (no personal identifiers) may be retained for analytics.\n\nFinancial records: Stripe transaction records retained for 7 years as required by applicable financial regulations.`,
          },
          {
            heading: '9. Cookies',
            body: `We use essential cookies for authentication and session management. We do not use advertising or tracking cookies. You can disable cookies in your browser, but this may affect login functionality.`,
          },
          {
            heading: '10. Children\'s Privacy',
            body: `BullSage is not directed at individuals under 18. We do not knowingly collect personal data from minors. If we become aware of such collection, we will delete the data promptly.`,
          },
          {
            heading: '11. Security',
            body: `We implement industry-standard security measures including encrypted data transmission (TLS), password hashing (via Supabase Auth), row-level security in our database, and access controls. No system is 100% secure; we will notify affected users of any data breach as required by applicable law.`,
          },
          {
            heading: '12. Changes to This Policy',
            body: `We may update this policy periodically. We will notify you by email of material changes at least 14 days before they take effect.`,
          },
          {
            heading: '13. Contact & Complaints',
            body: `Privacy inquiries: ${EMAIL}\n\nYou have the right to lodge a complaint with your local data protection authority:\n• Singapore: Personal Data Protection Commission (PDPC)\n• Hong Kong: Office of the Privacy Commissioner for Personal Data\n• Australia: Office of the Australian Information Commissioner (OAIC)\n• Malaysia: Department of Personal Data Protection`,
          },
        ],
      }}
      zh={{
        title: '隐私政策',
        sections: [
          {
            heading: '1. 关于我们',
            body: `BullSage 运营 ${DOMAIN}，一个 AI 投资教育平台。我们致力于保护您的个人数据。如有任何隐私问题，请通过 ${EMAIL} 联系我们。`,
          },
          {
            heading: '2. 我们收集的数据',
            body: `账户数据：电子邮件地址、密码（加密哈希）、显示名称、语言偏好、账户方案。\n\n使用数据：您分析的股票代码、自选股项目、报告历史、时间戳。\n\n支付数据：由 Stripe 处理的支付交易。BullSage 不存储信用卡号码。Stripe 的隐私政策适用于支付数据。\n\n技术数据：自动收集的 IP 地址、浏览器类型、设备类型、会话数据。`,
          },
          {
            heading: '3. 我们如何使用您的数据',
            body: `• 提供和改进 BullSage 服务\n• 验证您的账户并管理订阅\n• 生成和缓存 AI 分析报告\n• 发送交易性邮件（账户创建、支付收据）\n• 执行我们的服务条款并防止欺诈\n• 遵守法律义务`,
          },
          {
            heading: '4. 处理的法律依据（GDPR 和 PDPA）',
            body: `合同履行：为提供您注册的服务而必要的处理。\n\n合法利益：欺诈预防、安全、服务改进。\n\n同意：营销通信（您可以随时选择退出）。\n\n法律义务：遵守适用法律。`,
          },
          {
            heading: '5. 数据存储与第三方处理商',
            body: `我们的主要数据处理商：\n\n• Supabase（supabase.com）：数据库、身份验证。服务器位于 ap-southeast-1（新加坡）。适用 Supabase 的隐私政策。\n• Stripe（stripe.com）：支付处理。Stripe 通过 PCI-DSS 认证。\n• Google（AI Studio / Gemini API）：AI 推理。您的查询数据（股票代码、财务数据）可能由 Google 处理。不会将个人身份信息发送给 Gemini。\n• Vercel（vercel.com）：前端托管。可能记录 IP 地址。\n\n我们不会将您的个人数据出售给第三方。`,
          },
          {
            heading: '6. 跨境数据传输',
            body: `您的数据主要存储在新加坡（ap-southeast-1）。某些服务提供商可能在美国或欧洲处理数据。这些传输受适用数据保护法律下的适当保障措施约束。`,
          },
          {
            heading: '7. 您的权利',
            body: `根据您所在的司法管辖区，您有权：\n\n• 访问：请求您个人数据的副本\n• 更正：纠正不准确的数据\n• 删除：请求删除您的账户和数据\n• 可携带性：以结构化格式接收您的数据\n• 反对：反对基于合法利益的处理\n• 撤回同意：随时撤回同意\n\n如要行使这些权利，请发送电子邮件至 ${EMAIL}。我们将在 30 天内回复。`,
          },
          {
            heading: '8. 数据保留',
            body: `活跃账户：数据在您的账户使用期间及之后 12 个月内保留。\n\n已删除账户：核心账户数据在 30 天内删除。匿名化使用数据（无个人标识符）可能保留用于分析。\n\n财务记录：Stripe 交易记录根据适用财务法规保留 7 年。`,
          },
          {
            heading: '9. Cookie',
            body: `我们使用必要的 Cookie 进行身份验证和会话管理。我们不使用广告或跟踪 Cookie。您可以在浏览器中禁用 Cookie，但这可能影响登录功能。`,
          },
          {
            heading: '10. 儿童隐私',
            body: `BullSage 不针对 18 岁以下的个人。我们不会故意收集未成年人的个人数据。如我们意识到此类收集，将立即删除相关数据。`,
          },
          {
            heading: '11. 安全',
            body: `我们实施行业标准安全措施，包括加密数据传输（TLS）、密码哈希（通过 Supabase Auth）、数据库中的行级安全性以及访问控制。没有任何系统是 100% 安全的；我们将根据适用法律要求通知受影响的用户任何数据泄露事件。`,
          },
          {
            heading: '12. 政策变更',
            body: `我们可能会定期更新此政策。我们将在重大变更生效前至少 14 天通过电子邮件通知您。`,
          },
          {
            heading: '13. 联系与投诉',
            body: `隐私问题：${EMAIL}\n\n您有权向当地数据保护机构提出投诉：\n• 新加坡：个人数据保护委员会（PDPC）\n• 香港：个人资料私隐专员公署\n• 澳大利亚：澳大利亚信息专员办公室（OAIC）\n• 马来西亚：个人数据保护局`,
          },
        ],
      }}
    />
  );
}

// ─── SHARED ARTICLE COMPONENT ────────────────────────────────────────────────
function Article({ en, zh, lang }) {
  const content = lang === 'zh' ? zh : en;
  return (
    <div className="max-w-3xl mx-auto">
      <h1 className="text-3xl font-bold text-white mb-2">{content.title}</h1>
      <p className="text-sm text-gray-500 mb-10">
        {lang === 'zh' ? '最后更新：' : 'Last updated: '}{LAST_UPDATED}
      </p>
      <div className="space-y-8">
        {content.sections.map((s, i) => (
          <div key={i}>
            <h2 className="text-lg font-semibold text-[var(--gold)] mb-2">{s.heading}</h2>
            <div className="text-sm text-gray-400 leading-relaxed whitespace-pre-line">{s.body}</div>
          </div>
        ))}
      </div>
    </div>
  );
}

// ─── NAV TABS ────────────────────────────────────────────────────────────────
const TABS = [
  { key: 'disclaimer', label_zh: '免责声明', label_en: 'Disclaimer', path: '/legal/disclaimer' },
  { key: 'terms',      label_zh: '服务条款', label_en: 'Terms',      path: '/legal/terms'      },
  { key: 'privacy',    label_zh: '隐私政策', label_en: 'Privacy',    path: '/legal/privacy'    },
];

// ─── MAIN LEGAL PAGE ─────────────────────────────────────────────────────────
export default function Legal() {
  const { section } = useParams();
  const lang = localStorage.getItem('lang') || 'zh';
  const active = section || 'disclaimer';

  const renderSection = () => {
    switch (active) {
      case 'terms':      return <Terms lang={lang} />;
      case 'privacy':    return <Privacy lang={lang} />;
      default:           return <Disclaimer lang={lang} />;
    }
  };

  return (
    <div className="pt-20 pb-20 min-h-screen">
      <div className="max-w-4xl mx-auto px-6">
        {/* Tab nav */}
        <div className="flex gap-2 mb-10 border-b border-white/10 pb-0">
          {TABS.map(tab => (
            <Link
              key={tab.key}
              to={tab.path}
              className={`px-5 py-3 text-sm font-semibold rounded-t-lg transition border-b-2 -mb-px ${
                active === tab.key
                  ? 'border-[var(--gold)] text-[var(--gold)] bg-[var(--gold)]/5'
                  : 'border-transparent text-gray-500 hover:text-gray-300'
              }`}
            >
              {lang === 'zh' ? tab.label_zh : tab.label_en}
            </Link>
          ))}
        </div>

        {renderSection()}

        {/* Warning banner */}
        <div className="mt-12 bg-yellow-500/5 border border-yellow-500/20 rounded-xl p-5 text-sm text-yellow-400/80">
          {lang === 'zh'
            ? '⚠️ 本平台内容仅供教育目的，不构成投资建议。BullSage 不是持牌投资顾问。投资涉及风险，请咨询持牌专业人士后再做决定。'
            : '⚠️ All content on this platform is for educational purposes only and does not constitute investment advice. BullSage is not a licensed investment advisor. Investing involves risk; consult a licensed professional before making decisions.'}
        </div>
      </div>
    </div>
  );
}
